services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: ${DOMAIN_GITLAB}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${DOMAIN_GITLAB}"
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Оптимизация памяти (выделяем ~1GB под буферы БД)
        postgresql['shared_buffers'] = "1024MB"
        sidekiq['max_concurrency'] = 20
    ports:
      - '2222:22' # Для SSH-пуша
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${DOMAIN_GITLAB}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls.certresolver=myresolver"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - web

networks:
  web:
    external: true

