domain: "your.domain"
# Настройки Xray клиента
xray_server_address: "8.8.8.8"  # ЗАМЕНИТЕ НА ВАШ СЕРВЕР
xray_server_port: 42882                            # Порт сервера
xray_method: "2022-blake3-aes-256-gcm"            # Метод шифрования Shadowsocks
xray_password: "your pass"
xray_plugin: "v2ray-plugin"                       # Плагин для WebSocket транспорта
xray_plugin_opts: "tls;host={{ xray_server_address }};path=/ss"  # Опции плагина